In [ ]:
from pykeen.datasets import get_dataset
from pykeen.datasets.analysis import (
    get_entity_count_df,
    get_entity_relation_co_occurrence_df,
    get_relation_cardinality_types_df,
    get_relation_count_df,
    get_relation_functionality_df,
)

dataset = get_dataset(dataset="primekg")

In [13]:
from pykeen import models

models.DistMult.loss_default

pykeen.losses.MarginRankingLoss

In [ ]:
display(get_relation_count_df(dataset))

    relation_id    count              relation_label
0             0    28064             anatomy_anatomy
1             1    39774      anatomy_protein_absent
2             2  3036406     anatomy_protein_present
3             3   105772       bioprocess_bioprocess
4             4   289610          bioprocess_protein
5             5     9690           cellcomp_cellcomp
6             6   166804            cellcomp_protein
7             7    61350            contraindication
8             8    64388             disease_disease
9             9     2386  disease_phenotype_negative
10           10   300629  disease_phenotype_positive
11           11   160822             disease_protein
12           12  2672628                   drug_drug
13           13   129568                 drug_effect
14           14    50936                drug_protein
15           15     3250         exposure_bioprocess
16           16       20           exposure_cellcomp
17           17     4608            exposure_disease
18           18     4140           exposure_exposure
19           19       90            exposure_molfunc
20           20     2424            exposure_protein
21           21    18776                  indication
22           22    27148             molfunc_molfunc
23           23   139060             molfunc_protein
24           24     5136               off-label use
25           25     5046             pathway_pathway
26           26    85184             pathway_protein
27           27    37472         phenotype_phenotype
28           28     6660           phenotype_protein
29           29   642150             protein_protein

In [ ]:
display(get_entity_count_df(dataset))

        entity_id  count                                       entity_label
0               0      8                 'de novo' AMP biosynthetic process
1               1      6                 'de novo' CTP biosynthetic process
2               2      6        'de novo' GDP-L-fucose biosynthetic process
3               3     14                 'de novo' IMP biosynthetic process
4               4      6        'de novo' L-methionine biosynthetic process
...           ...    ...                                                ...
129257     129257      2  {[(2,6-difluorophenyl)carbonyl]amino}-N-(4-flu...
129258     129258      2  {[2-(1h-1,2,3-Benzotriazol-1-Yl)-2-(3,4-Difluo...
129259     129259      2  {[2-Amino-4-oxo-6,7-di(sulfanyl-κS)-3,5,5a,8,9...
129260     129260      2  {[5-(5-nitro-2-furyl)-1,3,4-oxadiazol-2-yl]thi...
129261     129261      2  {[7-(Difluoro-Phosphono-Methyl)-Naphthalen-2-Y...

[129262 rows x 3 columns]

In [4]:
display(get_entity_relation_co_occurrence_df(dataset))

,entity_id,relation_id,count,entity_label,relation_label
0,0,3,2,'de novo' AMP biosynthetic process,bioprocess_bioprocess
1,0,4,6,'de novo' AMP biosynthetic process,bioprocess_protein
2,1,3,2,'de novo' CTP biosynthetic process,bioprocess_bioprocess
3,1,4,4,'de novo' CTP biosynthetic process,bioprocess_protein
4,2,3,2,'de novo' GDP-L-fucose biosynthetic process,bioprocess_bioprocess
...,...,...,...,...,...
290260,129257,14,2,"{[(2,6-difluorophenyl)carbonyl]amino}-N-(4-flu...",drug_protein
290261,129258,14,2,"{[2-(1h-1,2,3-Benzotriazol-1-Yl)-2-(3,4-Difluo...",drug_protein
290262,129259,14,2,"{[2-Amino-4-oxo-6,7-di(sulfanyl-κS)-3,5,5a,8,9...",drug_protein
290263,129260,14,2,"{[5-(5-nitro-2-furyl)-1,3,4-oxadiazol-2-yl]thi...",drug_protein
290264,129261,14,2,{[7-(Difluoro-Phosphono-Methyl)-Naphthalen-2-Y...,drug_protein

In [ ]:
display(get_relation_functionality_df(dataset=dataset))

,relation_id,functionality,inverse_functionality,relation_label
0,0,0.500036,0.500036,anatomy_anatomy
1,1,0.181978,0.181978,anatomy_protein_absent
2,2,0.008230,0.008230,anatomy_protein_present
3,3,0.270790,0.270790,bioprocess_bioprocess
4,4,0.107417,0.107417,bioprocess_protein
5,5,0.430960,0.430960,cellcomp_cellcomp
6,6,0.126610,0.126610,cellcomp_protein
7,7,0.040065,0.040065,contraindication
8,8,0.264149,0.264149,disease_disease
9,9,0.530176,0.530176,disease_phenotype_negative
10,10,0.053697,0.053697,disease_phenotype_positive
11,11,0.091238,0.091238,disease_protein
12,12,0.001601,0.001601,drug_drug
13,13,0.016416,0.016416,drug_effect
14,14,0.184074,0.184074,drug_protein
15,15,0.227077,0.227077,exposure_bioprocess
16,16,0.650000,0.650000,exposure_cellcomp
17,17,0.167101,0.167101,exposure_disease
18,18,0.151208,0.151208,exposure_exposure
19,19,0.555556,0.555556,exposure_molfunc
20,20,0.322195,0.322195,exposure_protein
21,21,0.168513,0.168513,indication
22,22,0.411412,0.411412,molfunc_molfunc
23,23,0.161923,0.161923,molfunc_protein
24,24,0.240070,0.240070,off-label use
25,25,0.495046,0.495046,pathway_pathway
26,26,0.150909,0.150909,pathway_protein
27,27,0.397230,0.397230,phenotype_phenotype
28,28,0.296847,0.296847,phenotype_protein
29,29,0.028582,0.028582,protein_protein

In [6]:
display(get_relation_cardinality_types_df(dataset=dataset))

     relation_id relation_type  support  confidence          relation_label
0              0    one-to-one    28066    0.627136         anatomy_anatomy
1              0   one-to-many    28066    0.164783         anatomy_anatomy
2              0   many-to-one    28066    0.164783         anatomy_anatomy
3              0  many-to-many    28066    0.043298         anatomy_anatomy
4              1    one-to-one    14476    0.210270  anatomy_protein_absent
..           ...           ...      ...         ...                     ...
115           28  many-to-many     3954    0.199032       phenotype_protein
116           29    one-to-one    36708    0.005629         protein_protein
117           29   one-to-many    36708    0.069396         protein_protein
118           29   many-to-one    36708    0.069396         protein_protein
119           29  many-to-many    36708    0.855580         protein_protein

[120 rows x 5 columns]